name: Build and Release Executables

on:
  push:
    tags:
      - 'v*'

jobs:
  build_windows:
    runs-on: windows-latest
    permissions:
      contents: write  # Required for releases  
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build with PyInstaller
        run: pyinstaller --noconfirm main.spec
      - name: Zip release
        run: Compress-Archive -Path dist/UltimateStockTrader.exe -DestinationPath UltimateStockTrader-windows.zip
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: UltimateStockTrader-windows.zip
          tag_name: ${{ github.ref }}
          name: Ultimate Stock Trader ${{ github.ref }}
          draft: false
          prerelease: false

  build_macos:
    runs-on: macos-latest
    permissions:
      contents: write  # Required for releases
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build with PyInstaller
        run: pyinstaller --noconfirm main.spec
      - name: Zip release
        run: zip -r UltimateStockTrader-macos.zip dist/UltimateStockTrader
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: UltimateStockTrader-macos.zip
          tag_name: ${{ github.ref }}
          name: Ultimate Stock Trader ${{ github.ref }}
          draft: false
          prerelease: false

  build_linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for releases
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build with PyInstaller
        run: pyinstaller --noconfirm main.spec
      - name: Make executable
        run: chmod +x dist/UltimateStockTrader
      - name: Zip release
        run: zip -r UltimateStockTrader-linux.zip dist/UltimateStockTrader
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: UltimateStockTrader-linux.zip
          tag_name: ${{ github.ref }}
          name: Ultimate Stock Trader ${{ github.ref }}
          draft: false
          prerelease: false
